import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    welcomeBack: 'Welcome back,',
    champion: 'Champion',
    dailyGoal: 'Daily Goal',
    stayConsistent: 'Stay Consistent!',
    quickActions: 'Quick Actions',
    todaysWorkout: "Today's Workout",
    buildMuscle: 'Build muscle and burn fat',
    mealPlan: 'Meal Plan',
    egyptianNutrition: 'Egyptian nutrition',
    askCoach: 'Ask Coach',
    aiTrainer: 'AI personal trainer',
    todaysMotivation: "TODAY'S MOTIVATION",
    motivationQuote1: 'Discipline beats motivation.',
    motivationQuote2: 'Small progress is still progress.',
    motivationQuote3: 'Train hard. Recover harder.',
    motivationQuote4: 'Your body hears everything your mind says.',
    motivationQuote5: 'Consistency creates champions.',
    motivationQuote6: 'Do not skip the day you need most.',
    motivationQuote7: 'One workout at a time, one goal at a time.',

    home: 'Home',
    workouts: 'Workouts',
    meals: 'Meals',
    coach: 'Coach',
    more: 'More',

    getYourPlan: 'Get Your Personal Plan',
    age: 'Age',
    height: 'Height',
    weight: 'Weight',
    generatePlan: 'Generate My Plan',
    generating: 'Creating your plan...',
    yourCustomPlan: 'Your Custom Plan',
    workoutPlan: 'Workout Plan',
    nutritionPlan: 'Nutrition Plan',
    championStats: 'Champion Stats',
    clearPlan: 'Clear Plan',
    updatePlan: 'Update Plan',
    clearCurrentPlanConfirm: 'Clear current plan?',
    missingGroqApiKey: 'Please add your Groq API key to the .env file.',
    failedConnectAI: 'Failed to connect to AI. Disable ad blockers or check your internet.',
    failedGeneratePlan: 'Failed to generate plan. Check your API key or connection.',

    yourWeeklyPlan: 'Your weekly plan',
    today: 'Today',
    exercises: 'Exercises',
    restDay: 'Rest Day',
    restDayMsg: 'Recovery is part of the process. Let your muscles grow.',
    min: 'min',
    burns: 'Burns',
    kcal: 'kcal',
    fat: 'fat',
    sets: 'sets',
    reps: 'reps',

    egyptianMeals: 'Egyptian Nutrition',
    options: 'options',
    allMeals: 'All Meals',
    all: 'All',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    snack: 'Snack',
    preWorkout: 'Pre-Workout',
    postWorkout: 'Post-Workout',
    ingredients: 'Ingredients',
    howToPrepare: 'How to prepare',
    protein: 'Protein',
    carbs: 'Carbs',
    fats: 'Fats',
    portionSize: 'Portion Size',
    dietTip: 'Diet Tip',
    howMuchToEat: 'Suggested Intake',

    preWorkoutTip: 'Best Fat-Burning Pre-Workout Foods',
    preWorkoutFoods: 'Coffee, Green Tea, Oats, Bananas, Dates with Almonds',

    coachAI: 'Coach AI',
    online: 'Online',
    askCoachAnything: 'Ask Coach anything...',
    coachThinking: 'Coach is thinking...',
    listen: 'Listen',
    stop: 'Stop',
    coachInitialMessage: "Hey champ. I am Coach, your personal fitness AI. Ask me about workouts, nutrition, or your fitness journey.",
    coachMissingApiKey: 'I do not have your Groq API key yet. Add VITE_GROQ_API_KEY in .env.',
    coachLostThought: 'Sorry champ, I lost my train of thought.',
    coachInvalidApiKey: 'Your Groq API key looks invalid. Check it in .env.',
    coachRateLimit: 'Rate limit reached. Wait a bit and try again.',
    coachNetworkIssue: 'I had trouble connecting. Check internet or disable blockers.',
    coachErrorPrefix: 'Sorry champ, I had a connection issue:',

    Sunday: 'Sunday',
    Monday: 'Monday',
    Tuesday: 'Tuesday',
    Wednesday: 'Wednesday',
    Thursday: 'Thursday',
    Friday: 'Friday',
    Saturday: 'Saturday',

    chestWorkout: 'Chest & Triceps',
    backWorkout: 'Back & Biceps',
    legsWorkout: 'Legs & Glutes',
    shouldersWorkout: 'Shoulders & Core',
    chest: 'Chest',
    back: 'Back',
    legs: 'Legs',
    shoulders: 'Shoulders',
    recovery: 'Recovery',
    mixed: 'Mixed',

    ex_leg_extension: 'Leg Extensions',
    ex_leg_extension_desc: 'Sit on the machine, extend your legs fully.',

    language: 'Language',
    logout: 'Logout',
    settings: 'Settings',
    changeSchedule: 'Change training days',

    appTagline: 'Your Elite AI Fitness Coach',
    joinTeamTitle: 'Join the Team',
    welcomeChampionTitle: 'Welcome, Champion',
    signUp: 'Sign up',
    continue: 'Continue',
    withGoogle: 'with Google',
    orUseEmail: 'Or use email',
    emailAddress: 'Email address',
    password: 'Password',
    createAccount: 'Create Account',
    startTraining: 'Start Training',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    signIn: 'Sign in',
    joinTheTeam: 'Join the team',

    googleLoginFailed: 'Google login failed. Please try again.',
    pleaseFillAllFields: 'Please fill in all fields',
    accountCreatedExercisePrompt: 'Account created. Tell us which days you plan to exercise.',
    welcomeBackToast: 'Welcome back!',
    emailAlreadyRegistered: 'This email is already registered.',
    invalidCredentials: 'Invalid email or password.',
    authFailed: 'Authentication failed. Please check your credentials.',

    whenPlanExercise: 'When do you plan to exercise?',
    selectPlannedDays: 'Select the days you plan to train',
    selectAtLeastOneTrainingDay: 'Please select at least one training day',
    exerciseScheduleSaved: 'Exercise schedule saved!',
    errorOccurred: 'An error occurred',
    trainingDaysLabel: 'Training days:',
    noDaysSelected: 'No days selected',
    continueCta: 'Continue',
    changeLaterInSettings: 'You can change this later in settings',

    accessRestricted: 'Access Restricted',
    notRegisteredMessage: 'You are not registered to use this application. Please contact the app administrator for access.',
    ifErrorYouCan: 'If you believe this is an error, you can:',
    verifyCorrectAccount: 'Verify you are logged in with the correct account',
    contactAdmin: 'Contact the app administrator for access',
    tryLoginAgain: 'Try logging out and back in again',

    pageNotFound: 'Page Not Found',
    pageNotFoundLead: 'The page',
    pageNotFoundSuffix: 'could not be found in this application.',
    goHome: 'Go Home',

    footerCredit: 'Made by Mohamed Tamer | Powered by Firebase | Groq AI',
    gram: 'g',

    // Meal Specific Strings
    meal_ful: 'Ful Medames (Ultra Lean)',
    meal_ful_portion: '150g (boiled)',
    meal_ful_how: 'Eat half a bowl. Use 1/4 whole wheat bread maximum.',
    meal_ful_tip: 'Zero Oil. Add lemon, cumin, and chopped parsley for flavor.',
    meal_ful_ingredients: '150g Fava beans, 1/2 Lemon, 1 tsp Cumin, 1 Garlic clove, 1/4 Baladi bread',
    meal_ful_instr: 'Boil beans, mash with lemon and spices. No oil added.',

    meal_areesh: 'Low-Fat Areesh Cheese',
    meal_areesh_portion: '200g',
    meal_areesh_how: 'Best fit breakfast. Eat the full portion.',
    meal_areesh_tip: 'Top with lots of cucumber and green pepper to feel full.',
    meal_areesh_ingredients: '200g Quraish cheese, 1 large Cucumber, 1 Green pepper, 1 tsp Black seeds',
    meal_areesh_instr: 'Mix cheese with vegetables. Avoid adding any oil or cream.',

    meal_chicken: 'Grilled Chicken Breast (Lean)',
    meal_chicken_portion: '200g breast',
    meal_chicken_how: 'One large breast. Skip the rice for faster fat loss.',
    meal_chicken_tip: 'Remove all skin and visible fat before grilling.',
    meal_chicken_ingredients: '200g Skinless chicken breast, 2 tbsp Onion water, 1 tsp Thyme, 1/2 tsp Black pepper',
    meal_chicken_instr: 'Marinate in onion water and spices. Grill over charcoal or in oven.',

    meal_fish: 'Baked Sea Bass or Tilapia',
    meal_fish_portion: '250g fish',
    meal_fish_how: 'Eat one large fish with a huge green salad.',
    meal_fish_tip: 'Baking is much cleaner than frying. No flour coating.',
    meal_fish_ingredients: '250g Tilapia or Sea Bass, 2 Garlic cloves, 1 Lemon, 1 tsp Cumin, 1 Bell pepper',
    meal_fish_instr: 'Marinate with garlic/lemon, bake with peppers and onion slices.',

    meal_egg_whites: 'Fit Egg White Omelet',
    meal_egg_whites_portion: '6 Egg whites',
    meal_egg_whites_how: 'Perfect light dinner for muscle definition.',
    meal_egg_whites_tip: 'Use zero yolk for zero cholesterol and minimal fat.',
    meal_egg_whites_ingredients: '6 Egg whites, 100g Fresh spinach, pinch of Salt, 50g Mushrooms',
    meal_egg_whites_instr: 'Cook with a drop of vinegar to remove egg smell. Use non-stick pan.',

    meal_tuna: 'Lean Egyptian Tuna Salad',
    meal_tuna_portion: '1 can (drained)',
    meal_tuna_how: 'Eat directly with a fork. No bread.',
    meal_tuna_tip: 'Wash tuna with vinegar and water to remove excess sodium and oil.',
    meal_tuna_ingredients: '140g Canned tuna in water, 1/2 Onion, 1 tbsp Vinegar, pinch of Chili, 1 stalk Celery',
    meal_tuna_instr: 'Drain water/oil, mix with chopped veggies and vinegar.',

    meal_post_chicken: 'Post-Workout Chicken & Rice',
    meal_post_chicken_portion: '150g Chicken + 100g Rice',
    meal_post_chicken_how: 'Take within 60 mins of finishing your workout.',
    meal_post_chicken_tip: 'Steamed rice only. No butter or oil in the rice.',
    meal_post_chicken_ingredients: '150g Grilled chicken breast, 100g Steamed white rice, pinch of Cinnamon',
    meal_post_chicken_instr: 'Serve grilled chicken over steamed rice for fast recovery.',

    meal_protein_shake: 'Whey Protein Shake',
    meal_protein_shake_portion: '1 Scoop',
    meal_protein_shake_how: 'Best consumed immediately after training.',
    meal_protein_shake_tip: 'Use skimmed milk or water to keep calories minimal.',
    meal_protein_shake_ingredients: '30g Whey Protein Scoop, 300ml Water/Skimmed Milk',
    meal_protein_shake_instr: 'Mix in a shaker and drink immediately.',

    meal_termes: 'Boiled Lupin Beans (Termes)',
    meal_termes_portion: '1 Cup',
    meal_termes_how: 'Great high-protein snack for the evening.',
    meal_termes_tip: 'Use low salt to avoid water bloating.',
    meal_termes_ingredients: '100g Lupin beans, 1 tsp Cumin, 1 tbsp Lemon juice',
    meal_termes_instr: 'Boil until soft, season with cumin and lemon.',

    meal_coffee: 'Pre-Workout Coffee & Dates',
    meal_coffee_portion: 'Coffee + 2 Dates',
    meal_coffee_how: '30 mins before your training session.',
    meal_coffee_tip: 'Dates provide natural energy boost for your muscles.',
    meal_coffee_ingredients: '1 cup Black Coffee (Plain), 2 Medjool Dates',
    meal_coffee_instr: 'Brew coffee and have with dates for energy jump.',

    // Exercise Keys
    ex_bench_press: 'Bench Press',
    ex_bench_press_desc: 'Keep back flat and push through chest.',
    ex_incline_db_press: 'Incline Dumbbell Press',
    ex_incline_db_press_desc: 'Focus on upper chest, 45° angle.',
    ex_cable_flyes: 'Cable Flyes',
    ex_cable_flyes_desc: 'Squeeze at center for maximum contraction.',
    ex_deadlift: 'Deadlift',
    ex_deadlift_desc: 'Keep back straight, lift with your legs.',
    ex_lat_pulldown: 'Lat Pulldowns',
    ex_lat_pulldown_desc: 'Pull to upper chest, squeeze lats.',
    ex_squat: 'Barbell Squats',
    ex_squat_desc: 'Go below parallel for full leg growth.',
    ex_ohp: 'Overhead Press',
    ex_ohp_desc: 'Press straight up, engage your core.',
    ex_seated_row: 'Seated Cable Row',
    ex_seated_row_desc: 'Pull towards your waist, keep back straight.',
    ex_barbell_curl: 'Barbell Curls',
    ex_barbell_curl_desc: 'Curl the bar up, focus on biceps.',
    ex_leg_press: 'Leg Press',
    ex_leg_press_desc: 'Push the platform away using your heels.',
    ex_calf_raise: 'Calf Raises',
    ex_calf_raise_desc: 'Rise up on your toes, squeeze calves.',
    ex_lateral_raise: 'Lateral Raises',
    ex_lateral_raise_desc: 'Raise dumbbells to your sides, 90° angle.',
    ex_face_pull: 'Face Pulls',
    ex_face_pull_desc: 'Pull the rope towards your face, elbows out.',
    ex_cable_crunch: 'Cable Crunches',
    ex_cable_crunch_desc: 'Crunch down using your abs, not your hips.',
    ex_tricep_pushdown: 'Tricep Pushdowns',
    ex_tricep_pushdown_desc: 'Push down, lock elbows at the sides.',

    // Progress Tracker
    progress: 'Progress',
    weeklyProgress: 'Weekly Progress',
    streak: 'Streak',
    days: 'days',
    totalCaloriesBurned: 'Total Calories Burned',
    markComplete: 'Mark Today Complete',
    completed: 'Completed',
    noProgressYet: 'Start your fitness journey!',

    // Water Tracker
    waterIntake: 'Water Intake',
    glasses: 'glasses',
    waterGoal: 'Daily Goal: 8 Glasses',
    glassesConsumed: 'glasses consumed',

    // Body Measurements
    bodyMeasurements: 'Body Measurements',
    waist: 'Waist',
    arms: 'Arms',
    chestMeasure: 'Chest',
    saveMeasurement: 'Save Measurement',
    measurementSaved: 'Measurement saved!',
    weightOverTime: 'Weight Over Time',
    noMeasurements: 'No measurements yet',
    cm: 'cm',
    kg: 'kg',

    // Ramadan Mode
    ramadanMode: 'Ramadan Mode',
    suhoor: 'Suhoor',
    iftar: 'Iftar',
    postTarawih: 'Post-Tarawih',
    ramadanBanner: 'Ramadan Kareem 🌙',
    ramadanMealTip: 'Meals optimized for fasting',

    // Share Workout
    finishWorkout: 'Finish Workout',
    shareWorkout: 'Share',
    downloadCard: 'Download',
    workoutComplete: 'Workout Complete! 💪',
    exercisesCompleted: 'Exercises Completed',
    caloriesBurned: 'Calories Burned',

    // User Profile
    setupProfile: 'Set Up Your Profile',
    whatsYourGoal: "What's your goal?",
    bulk: 'Bulk',
    cut: 'Cut',
    maintain: 'Maintain',
    currentWeight: 'Current Weight (kg)',
    saveProfile: 'Save Profile',
    goalLabel: 'Goal',

    // Budget Meals
    budget: 'Budget',
    budgetMeals: 'Budget Meals',
    estimatedCost: 'Est. Cost',
    egp: 'EGP',
    meal_lentil_soup: 'Lentil Soup (Ads)',
    meal_lentil_soup_portion: '300ml bowl',
    meal_lentil_soup_how: 'Great as a starter or light meal.',
    meal_lentil_soup_tip: 'Add lemon juice for vitamin C absorption.',
    meal_lentil_soup_ingredients: '100g Red lentils, 1 Onion, 1 Tomato, 1 tsp Cumin, 1 Lemon',
    meal_lentil_soup_instr: 'Boil lentils with onion and tomato. Blend, season with cumin and lemon.',
    meal_egg_omelette: 'Egg Omelette',
    meal_egg_omelette_portion: '3 whole eggs',
    meal_egg_omelette_how: 'Quick protein-rich breakfast.',
    meal_egg_omelette_tip: 'Use non-stick pan, no oil needed.',
    meal_egg_omelette_ingredients: '3 Eggs, 1 Tomato, 1 Green pepper, Salt, Black pepper',
    meal_egg_omelette_instr: 'Beat eggs, pour in heated pan with chopped veggies. Fold when set.',
    meal_koshary: 'Koshary',
    meal_koshary_portion: 'Regular serving',
    meal_koshary_how: 'A full Egyptian meal rich in carbs and plant protein.',
    meal_koshary_tip: 'Eat moderate portions. Skip extra oil or ghee.',
    meal_koshary_ingredients: 'Rice, Lentils, Macaroni, Chickpeas, Tomato sauce, Fried onions',
    meal_koshary_instr: 'Layer cooked rice, lentils, and pasta. Top with tomato sauce and crispy onions.',

    // Logout Confirmation
    logoutConfirmTitle: 'Log Out',
    logoutConfirmMessage: 'Are you sure you want to log out?',
    cancel: 'Cancel',
  },
  ar: {
    welcomeBack: 'اهلا بعودتك،',
    champion: 'يا بطل',
    dailyGoal: 'هدف اليوم',
    stayConsistent: 'استمر في التمرين',
    quickActions: 'اجراءات سريعة',
    todaysWorkout: 'تمرين اليوم',
    buildMuscle: 'بناء العضلات وحرق الدهون',
    mealPlan: 'خطة الوجبات',
    egyptianNutrition: 'تغذية مصرية',
    askCoach: 'اسال المدرب',
    aiTrainer: 'مدرب ذكي شخصي',
    todaysMotivation: 'تحفيز اليوم',
    motivationQuote1: 'الالتزام اهم من الحماس.',
    motivationQuote2: 'التقدم الصغير يظل تقدما.',
    motivationQuote3: 'تمرن بقوة وتعافى بذكاء.',
    motivationQuote4: 'جسمك يسمع ما تقوله لعقلك.',
    motivationQuote5: 'الاستمرارية تصنع الابطال.',
    motivationQuote6: 'لا تتخطى اليوم الذي تحتاجه.',
    motivationQuote7: 'تمرين بعد تمرين.. هدف بعد هدف.',

    home: 'الرئيسية',
    workouts: 'التمارين',
    meals: 'الوجبات',
    coach: 'المدرب',
    more: 'المزيد',

    getYourPlan: 'احصل على خطتك الشخصية',
    age: 'العمر',
    height: 'الطول',
    weight: 'الوزن',
    generatePlan: 'انشاء خطتي',
    generating: 'جاري انشاء الخطة...',
    yourCustomPlan: 'خطتك المخصصة',
    workoutPlan: 'خطة التمرين',
    nutritionPlan: 'خطة التغذية',
    championStats: 'بيانات البطل',
    clearPlan: 'مسح الخطة',
    updatePlan: 'تحديث الخطة',
    clearCurrentPlanConfirm: 'هل تريد مسح الخطة الحالية؟',
    missingGroqApiKey: 'اضف مفتاح Groq API في ملف .env',
    failedConnectAI: 'فشل الاتصال بالذكاء الاصطناعي. تحقق من الانترنت او مانع الاعلانات.',
    failedGeneratePlan: 'فشل انشاء الخطة. تحقق من المفتاح او الاتصال.',

    yourWeeklyPlan: 'خطتك الاسبوعية',
    today: 'اليوم',
    exercises: 'التمارين',
    restDay: 'يوم راحة',
    restDayMsg: 'الراحة جزء من العملية. دع عضلاتك تتعافى.',
    min: 'دقيقة',
    burns: 'يحرق',
    kcal: 'سعرة',
    fat: 'دهون',
    sets: 'مجموعات',
    reps: 'عدات',

    egyptianMeals: 'تغذية مصرية',
    options: 'خيارات',
    allMeals: 'كل الوجبات',
    all: 'الكل',
    breakfast: 'فطور',
    lunch: 'غداء',
    dinner: 'عشاء',
    snack: 'سناك',
    preWorkout: 'قبل التمرين',
    postWorkout: 'بعد التمرين',
    ingredients: 'المكونات',
    howToPrepare: 'طريقة التحضير',
    protein: 'بروتين',
    carbs: 'كارب',
    fats: 'دهون',
    portionSize: 'حجم الحصة',
    dietTip: 'نصيحة الدايت',
    howMuchToEat: 'الكمية المقترحة',

    preWorkoutTip: 'افضل اطعمة قبل التمرين',
    preWorkoutFoods: 'القهوة، الشاي الاخضر، الشوفان، الموز، التمر مع اللوز',

    coachAI: 'المدرب الذكي',
    online: 'متصل',
    askCoachAnything: 'اسال المدرب اي شيء...',
    coachThinking: 'المدرب يفكر...',
    listen: 'استمع',
    stop: 'ايقاف',
    coachInitialMessage: 'اهلا يا بطل. انا المدرب الذكي الخاص بك. اسالني عن التمارين او التغذية او رحلتك الرياضية.',
    coachMissingApiKey: 'لا يوجد مفتاح Groq API بعد. اضفه في ملف .env باسم VITE_GROQ_API_KEY.',
    coachLostThought: 'اسف يا بطل، فقدت الفكرة للحظة.',
    coachInvalidApiKey: 'مفتاح Groq غير صحيح. تحقق منه في .env.',
    coachRateLimit: 'وصلنا للحد الاقصى من الطلبات. حاول بعد قليل.',
    coachNetworkIssue: 'واجهت مشكلة اتصال. تحقق من الانترنت او اوقف مانع الاعلانات.',
    coachErrorPrefix: 'اسف يا بطل، حدثت مشكلة:',

    Sunday: 'الاحد',
    Monday: 'الاثنين',
    Tuesday: 'الثلاثاء',
    Wednesday: 'الاربعاء',
    Thursday: 'الخميس',
    Friday: 'الجمعة',
    Saturday: 'السبت',

    chestWorkout: 'صدر وترايسبس',
    backWorkout: 'ظهر وبايسبس',
    legsWorkout: 'ارجل واليا',
    shouldersWorkout: 'اكتاف وبطن',
    chest: 'صدر',
    back: 'ظهر',
    legs: 'ارجل',
    shoulders: 'اكتاف',
    recovery: 'استشفاء',
    mixed: 'مختلط',

    ex_leg_extension: 'مد أرجل',
    ex_leg_extension_desc: 'اجلس على الجهاز، افرد رجليك تماماً للأمام.',

    language: 'اللغة',
    logout: 'تسجيل خروج',
    settings: 'الاعدادات',
    changeSchedule: 'تغيير ايام التمرين',

    appTagline: 'مدرب اللياقة الذكي الخاص بك',
    joinTeamTitle: 'انضم الى الفريق',
    welcomeChampionTitle: 'مرحبا ايها البطل',
    signUp: 'انشاء حساب',
    continue: 'متابعة',
    withGoogle: 'باستخدام جوجل',
    orUseEmail: 'او استخدم البريد الالكتروني',
    emailAddress: 'البريد الالكتروني',
    password: 'كلمة المرور',
    createAccount: 'انشاء الحساب',
    startTraining: 'ابدأ التمرين',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    dontHaveAccount: 'ليس لديك حساب؟',
    signIn: 'تسجيل الدخول',
    joinTheTeam: 'انضم للفريق',

    googleLoginFailed: 'فشل تسجيل الدخول عبر جوجل. حاول مرة اخرى.',
    pleaseFillAllFields: 'يرجى ملء جميع الحقول',
    accountCreatedExercisePrompt: 'تم انشاء الحساب. اخبرنا بايام التمرين المناسبة لك.',
    welcomeBackToast: 'مرحبا بعودتك!',
    emailAlreadyRegistered: 'هذا البريد مسجل بالفعل.',
    invalidCredentials: 'البريد الالكتروني او كلمة المرور غير صحيحة.',
    authFailed: 'فشلت المصادقة. تحقق من بياناتك.',

    whenPlanExercise: 'متى تخطط للتمرين؟',
    selectPlannedDays: 'اختر الايام التي تخطط للتمرين فيها',
    selectAtLeastOneTrainingDay: 'يرجى اختيار يوم تمرين واحد على الاقل',
    exerciseScheduleSaved: 'تم حفظ جدول التمارين!',
    errorOccurred: 'حدث خطأ',
    trainingDaysLabel: 'ايام التمرين:',
    noDaysSelected: 'لم يتم اختيار ايام',
    continueCta: 'متابعة',
    changeLaterInSettings: 'يمكنك تغيير هذا لاحقا من الاعدادات',

    accessRestricted: 'وصول مقيد',
    notRegisteredMessage: 'انت غير مسجل لاستخدام هذا التطبيق. تواصل مع مسؤول التطبيق لطلب الوصول.',
    ifErrorYouCan: 'اذا كنت تعتقد ان هذا خطأ، يمكنك:',
    verifyCorrectAccount: 'التأكد من تسجيل الدخول بالحساب الصحيح',
    contactAdmin: 'التواصل مع مسؤول التطبيق للحصول على صلاحية',
    tryLoginAgain: 'تسجيل الخروج ثم الدخول مرة اخرى',

    pageNotFound: 'الصفحة غير موجودة',
    pageNotFoundLead: 'الصفحة',
    pageNotFoundSuffix: 'غير موجودة في هذا التطبيق.',
    goHome: 'العودة للرئيسية',

    footerCredit: 'تم التطوير بواسطة Mohamed Tamer | مدعوم بواسطة Firebase و Groq AI',
    gram: 'جرام',

    meal_ful: 'فول مدمس خفيف (بدون زيت)',
    meal_ful_portion: '150 جرام (مسلوق)',
    meal_ful_how: 'نصف طبق فقط مع ربع رغيف خبز أسمر بحد أقصى.',
    meal_ful_tip: 'بدون زيت تماماً. استخدم الليمون والكمون والبقدونس للنكهة.',
    meal_ful_ingredients: '150 جم فول، نصف ليمونة، ملعقة صغيرة كمون، فص ثوم، ربع رغيف بلدي',
    meal_ful_instr: 'قم بسلق الفول، وهرسه مع الليمون والبهارات. لا تضف أي زيت.',

    meal_areesh: 'جبنة قريش دايت',
    meal_areesh_portion: '200 جرام',
    meal_areesh_how: 'أفضل فطور صحي. يمكنك تناول الحصة كاملة.',
    meal_areesh_tip: 'ضع الكثير من الخيار والفلفل الأخضر للشعور بالشبع.',
    meal_areesh_ingredients: '200 جم جبنة قريش، خيارة كبيرة، فلفل أخضر، ملعقة صغيرة حبة البركة',
    meal_areesh_instr: 'اخلط الجبنة مع الخضار المقطع. تجنب إضافة الزيت أو القشطة.',

    meal_chicken: 'صدور دجاج مشوية (بدون دهون)',
    meal_chicken_portion: '200 جرام صدور',
    meal_chicken_how: 'صدر دجاج كبير. تجنب الأرز لخسارة دهون أسرع.',
    meal_chicken_tip: 'قم بإزالة الجلد وأي دهون مرئية قبل الشوي.',
    meal_chicken_ingredients: '200 جم صدور دجاج، ملعقتين ماء بصل، ملعقة زعتر، نصف ملعقة فلفل أسود',
    meal_chicken_instr: 'تبل الدجاج في ماء البصل والبهارات ثم اشوه في الفرن أو على الفحم.',

    meal_fish: 'سمك مشوي في الفرن',
    meal_fish_portion: '250 جرام سمك',
    meal_fish_how: 'تناول سمكة كبيرة مع طبق سلطة خضراء كبير.',
    meal_fish_tip: 'الخبز في الفرن أنظف بكثير من القلي. لا تستخدم الدقيق.',
    meal_fish_ingredients: '250 جم سمك بلطي أو قاروص، فصين ثوم، ليمونة، ملعقة كمون، فلفل ألوان',
    meal_fish_instr: 'تبل السمك بالثوم والليمون واخبزه مع شرائح الفلفل والبصل.',

    meal_egg_whites: 'أومليت بياض البيض',
    meal_egg_whites_portion: 'بياض 6 بيضات',
    meal_egg_whites_how: 'عشاء خفيف مثالي لتقسيم العضلات.',
    meal_egg_whites_tip: 'بدون صفار لتقليل الكوليسترول والدهون تماماً.',
    meal_egg_whites_ingredients: 'بياض 6 بيضات، 100 جم سبانخ طازجة، رشة ملح، 50 جم مشروم',
    meal_egg_whites_instr: 'اطبخه في طاسة غير لاصقة مع نقطة خل لإزالة الرائحة.',

    meal_tuna: 'سلطة تونة مصرية (دايت)',
    meal_tuna_portion: 'علبة تونة (مصفاة)',
    meal_tuna_how: 'تناولها بالشوكة مباشرة بدون خبز.',
    meal_tuna_tip: 'اغسل التونة بالخل والماء لإزالة الصوديوم والزيوت الزائدة.',
    meal_tuna_ingredients: '140 جم تونة قطع، نصف بصلة، ملعقة خل، رشة شطة، عود كرفس',
    meal_tuna_instr: 'صفِّ التونة تماماً واخلطها مع الخضار المقطع والخل.',

    meal_post_chicken: 'وجبة دجاج وأرز بعد التمرين',
    meal_post_chicken_portion: '150 جم دجاج + 100 جم أرز',
    meal_post_chicken_how: 'تناولها خلال 60 دقيقة من نهاية التمرين.',
    meal_post_chicken_tip: 'أرز مسلوق أو على البخار فقط بدون أي زيت أو سمن.',
    meal_post_chicken_ingredients: '150 جم صدر دجاج، 100 جم أرز أبيض مسلوق، رشة قرفة',
    meal_post_chicken_instr: 'قدم الدجاج المشوي مع الأرز المسلوق لسرعة الاستشفاء.',

    meal_protein_shake: 'مخفوق بروتين (واي بروتين)',
    meal_protein_shake_portion: 'سكوب واحد',
    meal_protein_shake_how: 'يفضل تناوله مباشرة بعد التمرين.',
    meal_protein_shake_tip: 'استخدم الماء أو حليب خالي الدسم لتقليل السعرات.',
    meal_protein_shake_ingredients: '30 جم واي بروتين، 300 مل ماء أو حليب خالي الدسم',
    meal_protein_shake_instr: 'اخلطه في الشيكر واشربه فوراً.',

    meal_termes: 'ترمس مسلوق (سناك البروتين)',
    meal_termes_portion: 'كوب واحد',
    meal_termes_how: 'سناك ممتاز عالي البروتين لفترة المساء.',
    meal_termes_tip: 'قلل الملح لتجنب احتباس السوائل في الجسم.',
    meal_termes_ingredients: '100 جم ترمس، ملعقة صغيرة كمون، ملعقة عصير ليمون',
    meal_termes_instr: 'اسلق الترمس حتى ينضج ثم تبله بالكمون والليمون.',

    meal_coffee: 'قهوة وتمر قبل التمرين',
    meal_coffee_portion: 'قهوة +  تمرتين',
    meal_coffee_how: 'قبل جلسة التمرين بـ 30 دقيقة.',
    meal_coffee_tip: 'التمر يوفر طاقة طبيعية فورية لعضلاتك.',
    meal_coffee_ingredients: 'كوب قهوة سادة، 2 تمرة',
    meal_coffee_instr: 'حضر القهوة وتناولها مع التمر لطاقة تفجيرية.',

    ex_bench_press: 'ضغط صدر بالبار',
    ex_bench_press_desc: 'حافظ على استقامة ظهرك وادفع بصدرك.',
    ex_incline_db_press: 'ضغط صدر علوي بالدمبل',
    ex_incline_db_press_desc: 'ركز على الجزء العلوي، زاوية 45 درجة.',
    ex_cable_flyes: 'تفتيح كابل',
    ex_cable_flyes_desc: 'اعصر عضلات الصدر في المنتصف.',
    ex_deadlift: 'ديدليفت',
    ex_deadlift_desc: 'حافظ على ظهرك مفروداً، ارفع برجليك.',
    ex_lat_pulldown: 'سحب أمامي',
    ex_lat_pulldown_desc: 'اسحب للصدر العلوي بتركيز العضلات.',
    ex_squat: 'سكوات بالبار',
    ex_squat_desc: 'انزل لأسفل لنمو كامل لعضلات الرجل.',
    ex_ohp: 'ضغط كتف',
    ex_ohp_desc: 'ادفع للأعلى مباشرة مع شد البطن.',
    ex_seated_row: 'سحب أرضي',
    ex_seated_row_desc: 'اسحب للوسط مع استقامة الظهر.',
    ex_barbell_curl: 'تبادل بار',
    ex_barbell_curl_desc: 'ارفع البار مع التركيز على البايسبس.',
    ex_leg_press: 'دفع رجل',
    ex_leg_press_desc: 'ادفع المنصة بكعب القدم.',
    ex_calf_raise: 'سمانة',
    ex_calf_raise_desc: 'ارفع كعبك للأعلى مع عصر السمانة.',
    ex_lateral_raise: 'رفرفة جانبي',
    ex_lateral_raise_desc: 'ارفع الدمبل للجانبين بزاوية 90 درجة.',
    ex_face_pull: 'فيس بول',
    ex_face_pull_desc: 'اسحب الحبل باتجاه وجهك وكوعك للخارج.',
    ex_cable_crunch: 'طحن بطن بالكابل',
    ex_cable_crunch_desc: 'استخدم عضلات بطنك للطحن للأسفل.',
    ex_tricep_pushdown: 'ترايسبس كابل',
    ex_tricep_pushdown_desc: 'ادفع لأسفل مع تثبيت الكوع.',

    // Progress Tracker
    progress: 'التقدم',
    weeklyProgress: 'تقدم الأسبوع',
    streak: 'سلسلة',
    days: 'أيام',
    totalCaloriesBurned: 'إجمالي السعرات المحروقة',
    markComplete: 'تسجيل اليوم مكتمل',
    completed: 'مكتمل',
    noProgressYet: 'ابدأ رحلتك الرياضية!',

    // Water Tracker
    waterIntake: 'شرب المياه',
    glasses: 'أكواب',
    waterGoal: 'الهدف اليومي: 8 أكواب',
    glassesConsumed: 'أكواب تم شربها',

    // Body Measurements
    bodyMeasurements: 'قياسات الجسم',
    waist: 'الخصر',
    arms: 'الذراعين',
    chestMeasure: 'الصدر',
    saveMeasurement: 'حفظ القياس',
    measurementSaved: 'تم حفظ القياس!',
    weightOverTime: 'الوزن عبر الوقت',
    noMeasurements: 'لا توجد قياسات بعد',
    cm: 'سم',
    kg: 'كجم',

    // Ramadan Mode
    ramadanMode: 'وضع رمضان',
    suhoor: 'سحور',
    iftar: 'إفطار',
    postTarawih: 'بعد التراويح',
    ramadanBanner: 'رمضان كريم 🌙',
    ramadanMealTip: 'وجبات مُحسّنة للصيام',

    // Share Workout
    finishWorkout: 'إنهاء التمرين',
    shareWorkout: 'مشاركة',
    downloadCard: 'تحميل',
    workoutComplete: 'تم التمرين! 💪',
    exercisesCompleted: 'التمارين المكتملة',
    caloriesBurned: 'السعرات المحروقة',

    // User Profile
    setupProfile: 'إعداد ملفك الشخصي',
    whatsYourGoal: 'ما هو هدفك؟',
    bulk: 'تضخيم',
    cut: 'تنشيف',
    maintain: 'ثبات',
    currentWeight: 'الوزن الحالي (كجم)',
    saveProfile: 'حفظ الملف الشخصي',
    goalLabel: 'الهدف',

    // Budget Meals
    budget: 'اقتصادي',
    budgetMeals: 'وجبات اقتصادية',
    estimatedCost: 'التكلفة التقديرية',
    egp: 'ج.م',
    meal_lentil_soup: 'شوربة عدس',
    meal_lentil_soup_portion: 'طبق 300 مل',
    meal_lentil_soup_how: 'ممتازة كوجبة خفيفة أو مقبلات.',
    meal_lentil_soup_tip: 'أضف عصير الليمون لامتصاص فيتامين سي.',
    meal_lentil_soup_ingredients: '100 جم عدس أحمر، بصلة، طماطم، ملعقة كمون، ليمونة',
    meal_lentil_soup_instr: 'اسلق العدس مع البصل والطماطم. اخلطه وتبله بالكمون والليمون.',
    meal_egg_omelette: 'أومليت بيض',
    meal_egg_omelette_portion: '3 بيضات',
    meal_egg_omelette_how: 'فطور سريع غني بالبروتين.',
    meal_egg_omelette_tip: 'استخدم مقلاة غير لاصقة بدون زيت.',
    meal_egg_omelette_ingredients: '3 بيضات، طماطم، فلفل أخضر، ملح، فلفل أسود',
    meal_egg_omelette_instr: 'اخفق البيض واسكبه في المقلاة مع الخضار المقطع. اطوه عند النضج.',
    meal_koshary: 'كشري',
    meal_koshary_portion: 'طبق عادي',
    meal_koshary_how: 'وجبة مصرية كاملة غنية بالكربوهيدرات والبروتين النباتي.',
    meal_koshary_tip: 'كُل كمية معتدلة. تجنب الزيت أو السمن الزائد.',
    meal_koshary_ingredients: 'أرز، عدس، مكرونة، حمص، صلصة طماطم، بصل مقلي',
    meal_koshary_instr: 'رص الأرز والعدس والمكرونة. ضع الصلصة والبصل المقرمش.',

    // Logout Confirmation
    logoutConfirmTitle: 'تسجيل الخروج',
    logoutConfirmMessage: 'هل أنت متأكد من تسجيل الخروج؟',
    cancel: 'إلغاء',
  },
  es: {
    welcomeBack: 'Bienvenido,',
    champion: 'Campeón',
    dailyGoal: 'Meta Diaria',
    mealPlan: 'Plan de Comida',
    workouts: 'Entrenos',
    meals: 'Comidas',
    kcal: 'kcal',
    gram: 'g',
    protein: 'Proteína',
    carbs: 'Carbos',
    fats: 'Grasas',
    ingredients: 'Ingredientes',
    howToPrepare: 'Cocinando',
    allMeals: 'Todo',
    breakfast: 'Desayuno',
    lunch: 'Almuerzo',
    dinner: 'Cena',
    snack: 'Snack',
    preWorkout: 'Pre-Entreno',
    postWorkout: 'Post-Entreno',
    portionSize: 'Porción',
    dietTip: 'Consejo',
    howMuchToEat: 'Ingesta',

    ex_bench_press: 'Press de Banca',
    ex_bench_press_desc: 'Mantén la espalda recta y empuja.',
    ex_squat: 'Sentadillas',
    ex_squat_desc: 'Baja más allá del paralelo.',
  },
  it: {
    welcomeBack: 'Bentornato,',
    champion: 'Campione',
    dailyGoal: 'Obiettivo',
    mealPlan: 'Alimentazione',
    workouts: 'Allenamenti',
    meals: 'Pasti',
    kcal: 'kcal',
    gram: 'g',
    protein: 'Proteine',
    carbs: 'Carboidrati',
    fats: 'Grassi',
    ingredients: 'Ingredienti',
    howToPrepare: 'Preparazione',
    allMeals: 'Tutti',
    breakfast: 'Colazione',
    lunch: 'Pranzo',
    dinner: 'Cena',
    snack: 'Merenda',
    preWorkout: 'Pre-Workout',
    postWorkout: 'Post-Workout',
    portionSize: 'Porzione',
    dietTip: 'Consiglio',
    howMuchToEat: 'Dose',

    ex_bench_press: 'Panca Piana',
    ex_bench_press_desc: 'Mantieni la schiena piatta.',
    ex_squat: 'Squat',
    ex_squat_desc: 'Scendi sotto il parallelo.',
  },
  fr: {
    welcomeBack: 'Bon retour,',
    champion: 'Champion',
    dailyGoal: 'Objectif Quotidien',
    stayConsistent: 'Restez Constant !',
    quickActions: 'Actions Rapides',
    todaysWorkout: 'Entraînement du Jour',
    buildMuscle: 'Muscler et brûler les graisses',
    mealPlan: 'Plan de Repas',
    egyptianNutrition: 'Nutrition égyptienne',
    askCoach: 'Demander au Coach',
    aiTrainer: 'Entraîneur personnel IA',
    home: 'Accueil',
    workouts: 'Entraînements',
    meals: 'Repas',
    coach: 'Coach',
    more: 'Plus',
    today: 'Aujourd\'hui',
    exercises: 'Exercices',
    restDay: 'Jour de Repos',
    restDayMsg: 'La récupération fait partie du processus.',
    min: 'min',
    kcal: 'kcal',
    fat: 'lipides',
    sets: 'séries',
    reps: 'réps',
    protein: 'Protéines',
    carbs: 'Glucides',
    fats: 'Lipides',
    ingredients: 'Ingrédients',
    howToPrepare: 'Préparation',
    allMeals: 'Tous les Repas',
    breakfast: 'Petit Déjeuner',
    lunch: 'Déjeuner',
    dinner: 'Dîner',
    snack: 'En-cas',
    preWorkout: 'Pré-Entraînement',
    postWorkout: 'Post-Entraînement',
    portionSize: 'Portion',
    dietTip: 'Conseil Diet',
    howMuchToEat: 'Apport Suggéré',
    chestWorkout: 'Poitrine et Triceps',
    backWorkout: 'Dos et Biceps',
    legsWorkout: 'Jambes et Fessiers',
    shouldersWorkout: 'Épaules et Abdominaux',
    ex_bench_press: 'Développé Couché',
    ex_squat: 'Squat',
    ex_deadlift: 'Soulevé de Terre',
    ex_ohp: 'Développé Militaire',
  },
  de: {
    welcomeBack: 'Willkommen zurück,',
    champion: 'Champ',
    dailyGoal: 'Tagesziel',
    stayConsistent: 'Bleib konsequent!',
    quickActions: 'Schnellzugriff',
    todaysWorkout: 'Heutiges Training',
    buildMuscle: 'Muskeln aufbauen & Fett verbrennen',
    mealPlan: 'Ernährungsplan',
    egyptianNutrition: 'Ägyptische Ernährung',
    askCoach: 'Coach fragen',
    aiTrainer: 'KI Personal Trainer',
    home: 'Home',
    workouts: 'Training',
    meals: 'Mahlzeiten',
    coach: 'Coach',
    more: 'Mehr',
    today: 'Heute',
    exercises: 'Übungen',
    restDay: 'Ruhetag',
    restDayMsg: 'Erholung ist Teil des Prozesses.',
    min: 'Min',
    kcal: 'kcal',
    fat: 'Fett',
    sets: 'Sätze',
    reps: 'Wh.',
    protein: 'Eiweiß',
    carbs: 'Kohlenhydrate',
    fats: 'Fette',
    ingredients: 'Zutaten',
    howToPrepare: 'Zubereitung',
    allMeals: 'Alle Mahlzeiten',
    breakfast: 'Frühstück',
    lunch: 'Mittagessen',
    dinner: 'Abendessen',
    snack: 'Snack',
    preWorkout: 'Pre-Workout',
    postWorkout: 'Post-Workout',
    portionSize: 'Portion',
    dietTip: 'Tipp',
    howMuchToEat: 'Empfohlene Menge',
    chestWorkout: 'Brust & Trizeps',
    backWorkout: 'Rücken & Bizeps',
    legsWorkout: 'Beine & Po',
    shouldersWorkout: 'Schultern & Rumpf',
    ex_bench_press: 'Bankdrücken',
    ex_squat: 'Kniebeugen',
    ex_deadlift: 'Kreuzheben',
    ex_ohp: 'Schulterdrücken',
  }
};

// Simple loop to ensure all UI keys are present from EN if missing in ES/IT
['es', 'it', 'fr', 'de'].forEach(lang => {
  translations[lang] = { ...translations.en, ...translations[lang] || {} };
});

const supportedLanguages = [
  { code: 'en', label: 'English', base: 'en', dir: 'ltr', aiName: 'English' },
  { code: 'ar', label: 'العربية', base: 'ar', dir: 'rtl', aiName: 'Arabic' },
  { code: 'es', label: 'Español', base: 'es', dir: 'ltr', aiName: 'Spanish' },
  { code: 'fr', label: 'Français', base: 'fr', dir: 'ltr', aiName: 'French' },
  { code: 'de', label: 'Deutsch', base: 'de', dir: 'ltr', aiName: 'German' },
  { code: 'it', label: 'Italiano', base: 'it', dir: 'ltr', aiName: 'Italian' },
];

const motivationQuoteKeys = ['motivationQuote1', 'motivationQuote2', 'motivationQuote3', 'motivationQuote4', 'motivationQuote5', 'motivationQuote6', 'motivationQuote7'];

const getLanguageConfig = (code) => supportedLanguages.find((l) => l.code === code) || supportedLanguages[0];

const getDayOfYear = () => {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = Number(now) - Number(start);
  return Math.floor(diff / 86400000);
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('appLanguage') || 'en');

  useEffect(() => {
    const config = getLanguageConfig(language);
    localStorage.setItem('appLanguage', language);
    document.documentElement.dir = config.dir;
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    const { base } = getLanguageConfig(language);
    return translations[base]?.[key] || translations.en[key] || key;
  };

  const getDailyMotivationQuote = () => {
    const quoteKey = motivationQuoteKeys[getDayOfYear() % motivationQuoteKeys.length];
    return t(quoteKey);
  };

  const isRTL = getLanguageConfig(language).dir === 'rtl';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL, supportedLanguages, getDailyMotivationQuote }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage Error');
  return context;
}
